# Generated by Django 3.1.4 on 2021-01-10 09:28

from django.db import migrations, models


def link_transactions_categories(apps, schema_editor):
    Transaction = apps.get_model('system', 'Transaction')

    for transaction in Transaction.objects.all():
        transaction.categories.add(transaction.category)


class Migration(migrations.Migration):
    dependencies = [
        ('system', '0006_currency_decimal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(to='system.Category'),
        ),
        migrations.RunPython(link_transactions_categories),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
